[package]
edition = "2021"
name = "rgk-asm-lisp"
description = "RustGamingKit Lisp compiler"
version = "2022.12.14"

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
nom = { version = "7.1.1", features = ["alloc"] }
thiserror = "1.0.37"
rgk_core = { package = "rgk-core", path = "../../core" }
