[package]
edition = "2021"
name = "rgk-processors-6502"
description = "MOS 6502 support for RustGamingKit"
version = "2021.12.21"

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
rgk_core = { package = "rgk-core", path = "../../core" }
