[package]
edition = "2021"
name = "rgk-processors-core"
description = "Common functionality for processors for emulation"
version = "2023.2.6"

[features]
shared = ["dep:parking_lot"]

[dependencies]
bitflags = "1.3.2"
indexmap = "1.9.2"
parking_lot = { version = "0.12.1", optional = true }
