[package]
edition = "2021"
name = "rgk-patches-ips"
description = "IPS patch support for RustGamingKit"
version = "2021.12.18"

[features]
default = ["import"]
import = []
export = []

[dependencies]
byteorder = "1.4.3"
thiserror = "1.0.30"
rgk_core = { package = "rgk-core", path = "../../core" }
