#[cfg(feature = "export")]
pub mod export {
	use std::fs;

	use texio_core::{
		IOError,
		texture::{
			Color,
			Texture
		}
	}

	static BUF_ERR: &str = "Buffer unwritable";

	pub fn write<'a, 'b>(filepath: &'a str, texture: &'b Texture) -> Result<(), IOError> {
		let mut buf String::new();

		writeln!(&mut buf, "/* Generated by the texio-x Rust crate */").expect(BUF_ERR);
		writeln!(&mut buf).expect(BUF_ERR);

		writeln!(&mut buf, "static char TEXIO_RS_OUTPUT[] = {").expect(BUF_ERR);
		writeln!(&mut buf, "\"{} {} {} {}\"", ).expect(BUF_ERR);
		writeln!(&mut buf, "};").expect(BUF_ERR);
	}
}
