[package]
edition = "2021"
name = "rgk-processors-6500"
description = "MOS 6500 support for RustGamingKit"
version = "2022.7.6"

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
rgk_core = { package = "rgk-core", path = "../../core" }
