use meshio_core::tag4;

/// Chunk and sub-chunk tags
#[repr(u32)]
pub enum Tag {
	Attachments = tag4!(b"ATCH"),
	Bones = tag4!(b"BONE"),
	BindPoses = tag4!(b"BPOS"),
	Cameras = tag4!(b"CAMS"),
	CollisionShapes = tag4!(b"CLID"),
	CornEmitters = tag4!(b"CORN"),
	EventObjects = tag4!(b"EVTS"),
	FaceEffects = tag4!(b"FAFX"),
	GeosetAnimations = tag4!(b"GEOA"),
	Geosets = tag4!(b"GEOS"),
	GlobalSequences = tag4!(b"GLBS"),
	VertexGroups = tag4!(b"GNDX"),
	Helpers = tag4!(b"HELP"),
	EventTracks = tag4!(b"KEVT"),
	Layers = tag4!(b"LAYS"),
	Lights = tag4!(b"LITE"),
	MatrixIndices = tag4!(b"MATS"),
	Magic = tag4!(b"MDLX"),
	Model = tag4!(b"MODL"),
	MatrixGroups = tag4!(b"MTGC"),
	Materials = tag4!(b"MTLS"),
	Normals = tag4!(b"NRMS"),
	FaceGroups = tag4!(b"PCNT"),
	Pivots = tag4!(b"PIVT"),
	ParticleEmitters2 = tag4!(b"PRE2"),
	ParticleEmitters = tag4!(b"PREM"),
	FaceTypes = tag4!(b"PTYP"),
	Faces = tag4!(b"PVTX"),
	RibbonEmitters = tag4!(b"RIBB"),
	Sequences = tag4!(b"SEQS"),
	Skins = tag4!(b"SKIN"),
	Sounds = tag4!(b"SNDS"),
	Tangents = tag4!(b"TANG"),
	Textures = tag4!(b"TEXS"),
	TextureAnimations = tag4!(b"TXAN"),
	TextureCoordinateSets = tag4!(b"UVAS"),
	TextureCoordinates = tag4!(b"UVBS"),
	Version = tag4!(b"VERS"),
	Vertices = tag4!(b"VRTX"),
}

/// Tags for track chunks
#[repr(u32)]
pub enum TrackTag {
	AttachmentVisibility = tag4!(b"KATV"),
	CameraRotation = tag4!(b"KCRL"),
	CameraTranslation = tag4!(b"KCTR"),
	FresnelColor = tag4!(b"KFC3"),
	FresnelAlpha = tag4!(b"KFCA"),
	FresnelTeamColor = tag4!(b"KFTC"),
	GeosetAnimationColor = tag4!(b"KGAC"),
	GeosetAnimationAlpha = tag4!(b"KGAO"),
	NodeRotation = tag4!(b"KGRT"),
	NodeScale = tag4!(b"KGSC"),
	NodeTranslation = tag4!(b"KGTR"),
	LightColor = tag4!(b"KLAC"),
	AttenuationStartEnd = tag4!(b"KLAE"),
	Intensity = tag4!(b"KLAI"),
	AttenuationStart = tag4!(b"KLAS"),
	LightVisibility = tag4!(b"KLAV"),
	AmbientColor = tag4!(b"KLBC"),
	AmbientIntensity = tag4!(b"KLBI"),
	LayerAlpha = tag4!(b"KMTA"),
	EmissiveGain = tag4!(b"KMTE"),
	TextureID = tag4!(b"KMTF"),
	ParticleEmitter2Rate = tag4!(b"KP2E"),
	ParticleEmitter2Gravity = tag4!(b"KP2G"),
	ParticleEmitter2Latitude = tag4!(b"KP2L"),
	Length = tag4!(b"KP2N"),
	Variation = tag4!(b"KP2R"),
	ParticleEmitter2Speed = tag4!(b"KP2S"),
	ParticleEmitter2Visibility = tag4!(b"KP2V"),
	Width = tag4!(b"KP2W"),
	ParticleEmitterRate = tag4!(b"KPEE"),
	ParticleEmitterGravity = tag4!(b"KPEG"),
	ParticleEmitterLifespan = tag4!(b"KPEL"),
	ParticleEmitterSpeed = tag4!(b"KPES"),
	ParticleEmitterVisibility = tag4!(b"KPEV"),
	Longitude = tag4!(b"KPLN"),
	ParticleEmitterLatitude = tag4!(b"KPLT"),
	CornEmitterAlpha = tag4!(b"KPPA"),
	CornEmitterColor = tag4!(b"KPPC"),
	CornEmitterRate = tag4!(b"KPPE"),
	CornEmitterLifespan = tag4!(b"KPPL"),
	CornEmitterSpeed = tag4!(b"KPPS"),
	CornEmitterVisibility = tag4!(b"KPPV"),
	RibbonEmitterAlpha = tag4!(b"KRAL"),
	RibbonEmitterColor = tag4!(b"KRCO"),
	HeightAbove = tag4!(b"KRHA"),
	HeightBelow = tag4!(b"KRHB"),
	RibbonEmitterTexture = tag4!(b"KRTX"),
	RibbonEmitterVisibility = tag4!(b"KRVS"),
	TextureAnimationRotation = tag4!(b"KTAR"),
	TextureAnimationScale = tag4!(b"KTAS"),
	TextureAnimationTranslation = tag4!(b"KTAT"),
	TargetTranslation = tag4!(b"KTTR"),
}
